### ISSUE TITLE
Generar un wireframe

### ISSUE THREAD

**Issue by unjust** [Laboratoria/impl-data-lovers#5]
@DeysiVergara tienes un screenshot con que podemos generar un wireframe?

_Originally posted by @unjust in https://github.com/Laboratoria/DEV-999-data-lovers/issues/1#issuecomment-1645996669_

**Comment by DeysiVergara** [comment]
Esta supremamente sencillo, así esta ahora
https://drive.google.com/file/d/1rLl55vk1hNWC8dIWPxjbEFU48tl_mFba/view?usp=drive_link

**Comment by DeysiVergara** [comment]
Notas para mejora de wireframe:
Colocar label  para búsqueda por nombre.
Modificar la etiqueta de ordenar por tipo en filtrar por tipo.
Las estadísticas pueden ser definidas por la estudiante.
Más propiedades en la tarjeta, correspondiente a las propiedades de ordenar y filtrar. Por ejemplo el numero de pokemon o el elemento.
Anotaciones bajo el wirefrime.

**Comment by unjust** [comment]
Como parece estos para empezar?
![Data Lovers wfs (1)](https://github.com/Laboratoria/impl-data-lovers/assets/92090/1625aeb8-883c-4b79-86da-5fab34fa5b88)
![Data Lovers wfs](https://github.com/Laboratoria/impl-data-lovers/assets/92090/6cef16bc-643a-4d6d-bc1c-e0daaeb21c88)
